### ISSUE TITLE
Specifying opening book not optional

### ISSUE THREAD

**Issue by Claes1981** [kiudee/chess-tuning-tools#106]
* Chess Tuning Tools version: 0.7.0b2
* Python version: 3.8.5
* Operating System: Linux, OpenSUSE Tumbleweed

### Description

Until now I have been able to run the tuner without an opening book by pointing the tuner to an empty file (that only has the name  "something.pgn"). 

(I think that it has been discussed thoroughly on the Internet throughout the years about testing engines with or without books and with which books, maybe it has also been discussed about tuning with books. Personally, I prefer testing and tuning without any book, so the testing/tuning can't be biased towards one specific book, even if that also means the engine might not get tested/tuned on many specific openings.)

After updating Cutehess-cli to version 1.2.0 I get this error when using an empty book pgn file (using `--gp-initial-burnin 5` just to avoid having to wait only to demonstrate the error):

```
tune local --tuning-config Stockfish_20080713_bmi2_pgo_S200728-1442_b_config.json --data-path Stockfish_20080713_bmi2_pgo_S200728-1442_b.npz --logfile Stockfish_20080713_bmi2_pgo_S200728-1442_b.log --plot-path Stockfish_20080713_bmi2_pgo_S200728-1442_b --verbose --confidence 0.8 --gp-initial-burnin 5 --gp-burnin 50 --plot-every 5                      
2020-10-14 19:20:51,718 INFO     Importing 1021 existing datapoints. This could take a while...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [01:03<00:00,  7.97s/it]
2020-10-14 19:22:09,331 INFO     Importing finished.
2020-10-14 19:22:09,331 INFO     Starting iteration 1021
2020-10-14 19:22:34,953 INFO     Current optimum:
{'Threads': 6, 'SyzygyProbeDepth': 59, 'SyzygyProbeLimit': 2, 'Hash': 5785, 'Slow Mover': 544, 'Move Overhead': 3878}
2020-10-14 19:22:34,953 INFO     Estimated value: -0.4167 +- 0.1499
2020-10-14 19:22:34,953 INFO     80.0% confidence interval of the value: (-0.6088, -0.2246)
2020-10-14 19:22:35,156 INFO     80.0% confidence intervals of the parameters:
Parameter         Lower bound  Upper bound
------------------------------------------
Threads                     2            7
SyzygyProbeDepth           22          100
SyzygyProbeLimit            0            6
Hash                     1709         8142
Slow Mover                 49          880
Move Overhead              28         4159

2020-10-14 19:22:35,157 INFO     Testing {'Threads': 8, 'SyzygyProbeDepth': 63, 'SyzygyProbeLimit': 3, 'Hash': 3267, 'Slow Mover': 813, 'Move Overhead': 138}
2020-10-14 19:22:35,158 DEBUG    engines.json is prepared:
[{'command': 'nice --5 /partitions/Sandisk/xfs/media/data/chess/engines/Stockfish_development_versions/stockfish_20080713_bmi2_pgo', 'name': 'engine1', 'initStrings': ['setoption name Use NNUE value true', 'setoption name EvalFile value /partitions/Sandisk/xfs/media/data/chess/engines/Stockfish-NNUE/eval/Sergio-20200728-1442.bin', 'setoption name SyzygyPath value /partitions/nvme/xfs/chess/Syzygy', 'setoption name Contempt value 11'], 'protocol': 'uci'}, {'command': 'nice --5 /partitions/Sandisk/xfs/media/data/chess/engines/Stockfish_development_versions/stockfish_20080713_bmi2_pgo', 'name': 'engine2', 'initStrings': ['setoption name Use NNUE value true', 'setoption name EvalFile value /partitions/Sandisk/xfs/media/data/chess/engines/Stockfish-NNUE/eval/Sergio-20200728-1442.bin', 'setoption name Threads value 8', 'setoption name Hash value 1024', 'setoption name Contempt value 11', 'setoption name Move Overhead value 300'], 'protocol': 'uci'}]
2020-10-14 19:22:35,160 INFO     Start experiment
2020-10-14 19:22:35,168 DEBUG    Indexing opening suite...
2020-10-14 19:22:35,168 DEBUG    Warning: Start index larger than book size, wrapping after 0.
2020-10-14 19:22:35,274 INFO     Experiment finished (0.112984s elapsed).
Traceback (most recent call last):
  File "/home/claes/Chess-tuning-tools/env/bin/tune", line 8, in <module>
    sys.exit(cli())
  File "/home/claes/Chess-tuning-tools/env/lib64/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/claes/Chess-tuning-tools/env/lib64/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/claes/Chess-tuning-tools/env/lib64/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/claes/Chess-tuning-tools/env/lib64/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/claes/Chess-tuning-tools/env/lib64/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/claes/Chess-tuning-tools/env/lib64/python3.8/site-packages/tune/cli.py", line 459, in local
    score, error = parse_experiment_result(out_exp, **settings)
  File "/home/claes/Chess-tuning-tools/env/lib64/python3.8/site-packages/tune/local.py", line 127, in parse_experiment_result
    diffs = np.diff(array, axis=0, prepend=np.array([[0, 0, 0]]))
  File "<__array_function__ internals>", line 5, in diff
  File "/home/claes/Chess-tuning-tools/env/lib64/python3.8/site-packages/numpy/lib/function_base.py", line 1269, in diff
    a = np.concatenate(combined, axis)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
(env) claes@Lenovo-OpenSUSE:~/Chess-tuning-tools> cutechess-cli --version
cutechess-cli 1.2.0
Using Qt version 5.15.1
```

After downgrading again to the version "1.0.0.204+git.3ffafddd" from an OpenSUSE unofficial repository, the tuner works again as before.

This is of course after a change in Cutechess-cli, not in Chess Tuning Tools. But I think it would be nice to have an option or function in Chess Tuning Tools to be able to choose to not using a book, instead of the hack described above.

**Comment by kiudee** [comment]
It’s interesting that they chose to remove support for no opening book. I see some use cases where the user ensures ample exploration in the engine and does not need an opening book (e.g. using temperature).

That being said for tuning you have to be careful with using no opening book. You will definitely have the problem that many games are very similar and the optimal parameters could not generalize well. I recommend to use a very wide book like the `noob_3moves` one [here](https://github.com/official-stockfish/books).

**Comment by Claes1981** [comment]
Sorry, the headings of this issue was a bit unclear, I adjusted it now.
It is still possible to run Cutechess-cli alone without opening book in version 1.2.0. You just skip the book option on the command line.

It is with the tuner it is not possible to run without book anymore.

**Comment by kiudee** [comment]
Ah indeed, chess-tuning-tools currently raises an exception. I can easily change that.

**Comment by Claes1981** [comment]
Maybe it would be interesting to only let engine2 use a book, but not engine1. Cutechess-cli has an engine option "-book" that seems to be settable for each engine individually.

**Comment by Claes1981** [comment]
For the record, I discovered that it seems you can get the same behavior as no opening book by providing a PGN-file to Cutechess-cli with only the starting position. Like the only content of this start_pos.pgn:

`[FEN "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"]`

I let you decide if specifying an opening book should be optional or not in Chess Tuning Tools, feel free to close this issue if you prefer.

**Comment by kiudee** [comment]
I think that is a good solution/workaround. I like it since the user needs to be very explicit, if they want to use no opening book. In most cases this would be a mistake.
