### ISSUE TITLE
Error when trying to tune

### ISSUE THREAD

**Issue by lucametehau** [kiudee/chess-tuning-tools#123]
I just found out about chess tuning tools and i wanted to use it. Followed all the steps as in the guides, but when I try to tune I get the following error:

```
(venv) C:\Users\LMM\PycharmProjects\tune>tune local -c simple_tune.json
2021-05-03 18:16:06,485 INFO     Starting iteration 0
2021-05-03 18:16:06,486 INFO     Testing {'RazorCoef': 268}
2021-05-03 18:16:06,489 INFO     Start experiment
2021-05-03 18:16:06,499 INFO     Experiment finished (0.009971s elapsed).
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\LMM\PycharmProjects\tune\venv\Scripts\tune.exe\__main__.py", line 9, in <module>
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\tune\cli.py", line 459, in local
    score, error_variance = parse_experiment_result(out_exp, **settings)
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\tune\local.py", line 127, in parse_experiment_result
    diffs = np.diff(array, axis=0, prepend=np.array([[0, 0, 0]]))
  File "<__array_function__ internals>", line 6, in diff
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\numpy\lib\function_base.py", line 1270, in diff
    a = np.concatenate(combined, axis)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

```

My simple_tune.json file is:
```
{
   "engines": [
       {
           "command": "Clover.2.1.4-v2",
           "fixed_parameters": {
                "Threads": 1
           }
       },
       {
           "command": "Clover.2.1.4-v2.0",
           "fixed_parameters": {
                "Threads": 1
           }
       }
   ],
   "parameter_ranges": {
       "RazorCoef": "Integer(200, 400)"
   },
   "engine1_tc": "10+0.1",
   "engine2_tc": "10+0.1",
   "rounds": 20,
   "opening_file": "4moves_noob.pgn",
   "concurrency": 2
}
```

**Comment by kiudee** [comment]
Thank you for the log and configuration.
Which version of cutechess-cli are you using? It looks like the parser is not able to deal with the result it receives.

**Comment by lucametehau** [comment]
Latest, 1.2.0.

**Comment by kiudee** [comment]
Could you try running the tuner again with verbose logging activated?
```
tune local -c simple_tune.json --verbose
```

**Comment by lucametehau** [comment]
Sure. I got:

```
(venv) C:\Users\LMM\PycharmProjects\tune>tune local -c simple_tune.json --verbose
2021-05-03 19:12:28,354 INFO     Starting iteration 0
2021-05-03 19:12:28,358 INFO     Testing {'RazorCoef': 268}
2021-05-03 19:12:28,358 DEBUG    engines.json is prepared:
[{'command': 'Clover.2.1.4-v2', 'name': 'engine1', 'initStrings': ['uci', 'setoption name Threads value 1'], 'protocol': 'uci'}, {'command': 'Clover.2.1.4-v2.0', 'name': 'engine2', 'initStrings': ['uci', 'setoptio
n name Threads value 1'], 'protocol': 'uci'}]
2021-05-03 19:12:28,363 INFO     Start experiment
2021-05-03 19:12:28,384 INFO     Experiment finished (0.020083s elapsed).
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\LMM\PycharmProjects\tune\venv\Scripts\tune.exe\__main__.py", line 9, in <module>
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\tune\cli.py", line 459, in local
    score, error_variance = parse_experiment_result(out_exp, **settings)
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\tune\local.py", line 127, in parse_experiment_result
    diffs = np.diff(array, axis=0, prepend=np.array([[0, 0, 0]]))
  File "<__array_function__ internals>", line 6, in diff
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\numpy\lib\function_base.py", line 1270, in diff
    a = np.concatenate(combined, axis)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
```

**Comment by kiudee** [comment]
Ok, curious. Since there is no log output at all, it means that cutechess-cli was not producing any output, which is why the parser received an empty string.

**Comment by lucametehau** [comment]
So it this because of cutechess? Should I reinstall it?

**Comment by kiudee** [comment]
The things I would check first are:

- Is the `engines.json` file constructed correctly?
- Is the cutechess-cli in the path or a binary file in the local folder?
- Does running cutechess-cli on the constructed `engines.json` file manually work?
```
cutechess-cli -engine conf=engine1 tc=1 -engine conf=engine2 tc=1
```

**Comment by lucametehau** [comment]
1. This is the ```engines.json``` file:
```

[
    {
        "command": "Clover.2.1.4-v2",
        "initStrings": [
            "uci",
            "setoption name Threads value 1",
            "setoption name RazorCoef value 268"
        ],
        "name": "engine1",
        "protocol": "uci"
    },
    {
        "command": "Clover.2.1.4-v2.0",
        "initStrings": [
            "uci",
            "setoption name Threads value 1"
        ],
        "name": "engine2",
        "protocol": "uci"
    }
]
```

2. Yes, cutechess-cli is in the Path. I also added cutechess-cli.exe inside the folder with the engines, opening book and .json file

3. How do I set the ```engines.json``` file for cutechess? (Sorry, it's my first time using cutechess-cli, I only used the cutechess app)

**Comment by kiudee** [comment]
>     2. How do I set the `engines.json` file for cutechess? (Sorry, it's my first time using cutechess-cli, I only used the cutechess app)
> 
Using the command line (Press windows key and then type cmd), navigate to the folder:
```
cd c:\path\to\the\folder\
```
and run
```
cutechess-cli -engine conf=engine1 tc=1 -engine conf=engine2 tc=1
```
It should read the `engines.json` automatically.

**Comment by lucametehau** [comment]
Hm... I removed cutechess-cli.exe and replaced ```"command": "Clover.2.1.4-v2"```, with ```"command": "C:\\Users\\LMM\\PycharmProjects\\tune\\Clover.2.1.4-v2.exe"``` and same with the other engine and now cutechess-cli runs with your command. Problem is now I get this error:
```
(venv) C:\Users\LMM\PycharmProjects\tune>tune local -c simple_tune.json --verbose
2021-05-03 21:19:59,658 INFO     Starting iteration 0
2021-05-03 21:19:59,659 INFO     Testing {'RazorCoef': 268}
2021-05-03 21:19:59,659 DEBUG    engines.json is prepared:
[{'command': 'C:\\Users\\LMM\\PycharmProjects\\tune\\Clover.2.1.4-v2.exe', 'name': 'engine1', 'initStrings': ['uci', 'setoption name Threads value 1'], 'protocol': 'uci'}, {'command': 'C:\\Users\\LMM\\PycharmProje
cts\\tune\\Clover.2.1.4-v2.0.exe', 'name': 'engine2', 'initStrings': ['uci', 'setoption name Threads value 1'], 'protocol': 'uci'}]
2021-05-03 21:19:59,663 INFO     Start experiment
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\LMM\PycharmProjects\tune\venv\Scripts\tune.exe\__main__.py", line 9, in <module>
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\tune\cli.py", line 451, in local
    for output_line in run_match(**settings):
  File "c:\users\lmm\pycharmprojects\tune\venv\lib\site-packages\tune\local.py", line 375, in run_match
    string_array, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
And I think it's because it can't find cutechess-cli, even though I added it in Path. More over, when I try to run ```cutechess-cli -help``` in the folder, I get this:
```
(venv) C:\Users\LMM\PycharmProjects\tune>cutechess-cli -help
'cutechess-cli' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by kiudee** [comment]
Indeed it looks like the updated Path is not yet available. See if restarting the PC takes care of it.

**Comment by lucametehau** [comment]
If Path wouldn't have been available, I wouldn't be able to use cutechess-cli in cmd. But I'll try restarting and see if it works.

**Comment by lucametehau** [comment]
Aaand it worked. Thank you very much for the help!

**Comment by kiudee** [comment]
Glad to hear that! Feel free to open issues for any usage questions/problems you encounter.
